# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/npm_publish:latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: npm-cli-login -u jfgarcia268 -p ${{ secrets.NPM_PASS }}  -e jf.garcia268@gmail.com
    - run: pwd 
    - run: ls
    - run: npm config set unsafe-perm=true
    - run: npm install .
    - run: npm publish .