# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/npm_publish:latest
    steps:  
    - env:
      NPM_TOKEN: ${{ secrets.NPM_PASS }}
    - uses: actions/checkout@v2
    - run: npm login
    - run: npm config set unsafe-perm=true
    - run: npm install .
    - run: npm publish .