name: Publish Beta

on:
  pull_request:
    branches:
      - beta
    types: [closed]
  workflow_dispatch:  
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: agutierrezdelvalle/npm_publish:latest
    steps:  
    - uses: actions/checkout@v2
    - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PASS }}
    - run: npm config set unsafe-perm=true
    - run: npm install .
    - run: npm publish . --tag beta

